### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SoraKohaku** [jackytank/jackytank.github.io#3]
Error: querySrv ENOTFOUND _mongodb._tcp.jackcluster.hmvat.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:45:19) {
  errno: undefined,
  code: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.jackcluster.hmvat.mongodb.net'
}

**Comment by jackytank** [comment]
oh you need to provide your own mongodb credentials, because I'm lazy so I hard coded my own mongodb credential of jackcluster to the repo

**Comment by SoraKohaku** [comment]
Did they auto create after that

**Comment by jackytank** [comment]
I didn't fully comprehend your question, the point is you need to provide your own MongoDB credential whether it's localhost or cloud mongo
